### PR TITLE
Swap alsa_midi slave driver port-name suffixes ("out" for capture, "in" for playback)

### PR DESCRIPTION
**Pull request by rncbc**
Swap alsa_midi slave driver port-name suffixes:
- "out" for capture, readable/output ports (=JackPortIsOutput);
- "in" for playback, writable/input ports (=JackPortIsInput)

### CODE REVIEW

**Comment by rncbc** [comment]
imho. these "in"/"out" suffixes shouldn't be there at all.

**Comment by joshdekock** [comment]
why do you think they should be swapped? Input means audio is coming in, and output means that audio is going out. You read from an input, and write to an output. Swapping them doesn't really make sense.

**Comment by rncbc** [comment]
first, this is not audio ports. but that's not the point here anyway,

second, the "in" suffix should always be there on ports that are effective flagged/typed as `JackPortIsInput` (writable/input ports); likewise, the "out" suffix should be on ports that are `JackPortIsOutput` (readable/output ports).

third, just like that machine(program) vs. human(user) POV naming convention and confusion is better off NOT to be be engraved as visible text to humans, i proposed the "(in)" and "(out)" literals to get dropped from alsa_midi port names--they add nothing but this kind of programmer vs. user dialectics.

and fourth, last but not least, they way those suffixes are now, are plain wrong, misleading and piles up fire to the confusion; have you ever looked to them on a connection-manager UI? say qjackctl, at all? 

cheers

**Comment by pauldavisthefirst** [comment]
I agree that they should be swapped.

If we drop the suffixes, then these two ports:

      alsa_midi:Midi Through Port-0 in
      alsa_midi:Midi Through Port-0 out

become indistinguishable based on name. Since JACK offers quite a number of port-related capabilities based on name, I don't see how it can be OK to end up with ports that use the same name. In fact, it isn't even legal.

**Comment by pauldavisthefirst** [comment]
I've applied and pushed the in/out switch.

**Pull request closed without merging**
