### PR TITLE
config/cpu cleanup

### LINKED ISSUE #56: Useless files in config/cpu
There seem to be lots of files in config/cpu which are not used anywhere.

Only these directories are used:
* `config/cpu/generic`
* `config/cpu/i386`
* `config/cpu/i486`
* `config/cpu/powerpc`

I suggest removing all the non-generic `atomicity.h` files which seem redundant, wire up the unused `cycles.h` files, and completely remove the other directories.

### PR DESCRIPTION
**Pull request by jcowgill**
Fixes #56

It turns out all the `cycles.h` files are also unused, so I've removed those as well. The `atomicity.h` files could also be replaced with the generic implementation but I wasn't sure if that was kept for a reason (other platforms?)

### CODE REVIEW

**Comment by enoposix** [comment]
Did you test the other platforms? (Do they still work?)

**Comment by jcowgill** [comment]
No, I haven't. I simply removed the files based on them never being included anywhere else in the jack codebase. In theory this PR has absolutely no effect on any platform.

**Comment by adiknoth** [comment]
@jcowgill I think we should replace the atomicity.h files with the generic one - pretty much everyone should be using the compiler builtins by now.

If you want to send another PR, I'm happy to merge.


Thanks

**Comment by jcowgill** [comment]
@adiknoth OK I can send another PR. Does jack have a minimum GCC version? I ask because the `__sync` functions are deprecated and should be replaced if possible. For GCC, `__sync*` requires 4.1, `__atomic*` requires 4.7, and C11's `stdatomic.h` requires 4.9.

**Comment by adiknoth** [comment]
Let's use C11 if available or 4.7 if not. GCC 4.9 was released in April 2014, that's almost three years, 4.7 in March 2012, almost five years.

According to wikipedia: "A standard macro __STDC_VERSION__ is defined with value 201112L to indicate that C11 support is available."

So we can have something like

#if __STDC_VERSOIN__ >= 201112L
#include <stdatomic.h>
...
#else 
...
#fi 

Thanks!

**Pull request merged**
