### PR TITLE
Autotool fixes

### PR DESCRIPTION
**Pull request by erikd**
And a whitespace fixup.

### CODE REVIEW

**Comment by pauldavisthefirst** [comment]
Thanks. I'll get to this (and some other pull requests) after Ardour 4.5 gets out the door.

**Comment by erikd** [comment]
Yep, thats fine. Thanks.

**Comment by erikd** [comment]
Ping?

**Comment by pauldavisthefirst** [comment]
see recent mail to jack-devel.

it will happen.

**Comment by pauldavisthefirst** [comment]
These changes do not work correctly with the version of autotools present in Debian Jessie (at least). It enters an endless loop inside the generated configure script. Just another reason why autotool stuff sucks, since no doubt it works fine for you.

**Comment by erikd** [comment]
I just tried it on Jessie and can confirm your report of an endless loop. A little preliminary debugging suggests that this is due to incorrect/duplicate usage of `AC_INIT` (which autoconf was already warning about). I'll figure out the best way to fix that some time today and provide an updated version of this patch.

**Comment by erikd** [comment]
Test on Debian Testing/Unstable and Debian Jessie.

**Comment by erikd** [comment]
I suspect the "Syn tools submodule" commit is incorrect, but unsure of how to submit it the right way.

**Comment by pauldavisthefirst** [comment]
make maintainer-clean now fails, with this error:

Makefile:621: ../libjack/.deps/libjackserver_la-unlock.Plo: No such file or directory
Makefile:622: ../libjack/.deps/libjackserver_la-uuid.Plo: No such file or directory
make[1]: *** No rule to make target '../libjack/.deps/libjackserver_la-uuid.Plo'.  Stop.
make[1]: Leaving directory '/usr/local/music/src/jack/jackd'
Makefile:534: recipe for target 'maintainer-clean-recursive' failed

**Comment by erikd** [comment]
Thanks. I'll fix that.

**Comment by erikd** [comment]
Have now tested on Debian Testing and Jessie using:

```
./autogen.sh && ./configure --prefix=/usr && make clean all clean dist maintainer-clean
```

No issues found.

This commit does however need to patch for the `tools` submodule in https://github.com/jackaudio/tools/issues/6 .

**Comment by erikd** [comment]
Thanks @pauldavisthefirst !

**Pull request merged**
